## Global Prometheus Server Config
global:
  scrape_interval: 15s
  evaluation_interval: 60s

## Rules and alerts are read from the specified file(s)
rule_files:
  - /etc/prometheus/rules/*.yaml

## Prometheus Server Config
scrape_configs:
- job_name: 'prometheus.htdom.lan'
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
    - targets: ['prometheus.htdom.lan']

- job_name: 'grafana.htdom.lan'
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
    - targets: ["grafana.htdom.lan"]

- job_name: 'loki.htdom.lan'
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
    - targets: ["loki.htdom.lan"]

- job_name: 'mina.htdom.lan'
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
    - targets: ["mina.htdom.lan:9100"]

- job_name: 'caddy.htdom.lan'
  scheme: https
  metrics_path: /metrics
  tls_config:
    insecure_skip_verify: true
  static_configs:
    - targets: ["caddy.htdom.lan"]

- job_name: 'blackbox-dns-check'
  metrics_path: /probe
  params:
    module: [ dns ]
  static_configs:
    - targets:
        - 192.168.178.50
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: target
    - target_label: __address__
      replacement: blackbox.htdom.lan:9115      

- job_name: 'blackbox-http-check'
  metrics_path: /probe
  params:
    module: [ http_2xx ]
  static_configs:
    - targets:
      - https://caddy.htdom.lan/metrics
      - https://grafana.htdom.lan/metrics
      - https://loki.htdom.lan/ready
      - https://prometheus.htdom.lan/metrics
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: target
    - target_label: __address__
      replacement: blackbox.htdom.lan:9115
