interface=eth0
domain=htdom.local
local=/htdom.local/
host-record=blackbox.htdom.local,192.168.178.3
host-record=caddy.htdom.local,192.168.178.3
host-record=dns.htdom.local,192.168.178.3
host-record=grafana.htdom.local,192.168.178.3
host-record=loki.htdom.local,192.168.178.3
host-record=mina.htdom.local,192.168.178.3
host-record=prometheus.htdom.local,192.168.178.3

# Weiterleitung aller anderen Anfragen an den Upstream-DNS Server
server=192.168.178.1
