interface=eth0
domain=htdom.lan
local=/htdom.lan/
host-record=blackbox.htdom.lan,192.168.178.3
host-record=caddy.htdom.lan,192.168.178.3
host-record=dc.htdom.lan,192.168.178.3
host-record=dns.htdom.lan,192.168.178.3
host-record=grafana.htdom.lan,192.168.178.3
host-record=loki.htdom.lan,192.168.178.3
host-record=mina.htdom.lan,192.168.178.3
host-record=oidc.htdom.lan,192.168.178.3
host-record=prometheus.htdom.lan,192.168.178.3

# Weiterleitung aller anderen Anfragen an den Upstream-DNS Server
server=192.168.178.1
